language: python
python:
- '2.6'
- '2.7'
install: 
    - pip install --find-links http://peak.telecommunity.com/snapshots/ -e .[dev]
script: nosetests
deploy:
  provider: pypi
  user: mmarchini
  password:
    secure: i+70vrfF64hxGXaBs1Zjy7kNnTKy0FnUDfTfWYJ8KroOZdZAt0Q4NUYkagGTubPupl7UXBzdB4u55GN84E/5C+v0HHN2QgNqHOoYV2qkuTGb2OTgdcRBluYkrLVLaRaFle8g4eV47qU/iMfE6SdaKeSIurK+FT4clAP8N8EBQvw60i+HxhL9TVF8LBIFuwDI2gmaUx0dOicWEYNnDITyX6Zq3t74Y6tcZcDVxp4rXh9FgDUNmAooP2XUozlq62kBugWmDSlm7N/TdGrF9XDi9Qm4VWeKub6uW0V5U6YORTj5hGVe+a9zYd3RzbX1secdPVZTrauhou0QQN9SoSRV8xdp7gZwlTpN8//zr2z5uiCtU4Fp1bsGT43wrHiqzCE7ZM1W+ueGzvN7fgTc/QCktjyTFGKNR8z1qgGmC6D9BQzAX8a5qPSlZ6b0d76ldrgYfgpMUonxY+Fd6F/wHuKf2bxrXbnsb5FpTCNc6e7j5h69fbzAolJ5LI5ULlMSuBZKGeTEKs6McBCyFEC/qR1JeQ8wMYkJuYP7Vq7r9y3xcroSuGqgLHRSSX5jyKB4opASoJDvJ1Q3y+qVZID/H6RcjdIN89pXkPBB6YGw++lcAVeKoLAN8BIj2S3Pgmcpx6V2ojEGpvG8PzCOm22Lh+0AechfbNpmRutps6iJBQ/aghY=
  on:
    tags: true

